[versions]
agp = "8.12.0"
annotations = "1.9.1"

[libraries]
androidx-annotations = { group = "androidx.annotation", name = "annotation", version.ref = "annotations" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
